server:
    port: 8080

spring:
    cache:
        type: redis
        redis:
            time-to-live: 600000
            cache-null-values: true

    datasource:
        url: jdbc:mysql://homestead.test/lmfds_post?serverTimezone=Asia/Seoul&characterEncoding=utf-8
        username: homestead
        password: secret
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                "[format_sql]": true
                "[show_sql]": true
    data:
        redis:
            host: homestead.test
            port: 6379
